" System gvimrc file for MacVim
"
" Maintainer:	Bjorn Winckler <bjorn.winckler@gmail.com>
" Last Change:	Sun Aug 29 2009
"
" This is a work in progress.  If you feel so inclined, please help me improve
" this file.


" Make sure the '<' and 'C' flags are not included in 'cpoptions', otherwise
" <CR> would not be recognized.  See ":help 'cpoptions'".
let s:cpo_save = &cpo
set cpo&vim

if !exists("syntax_on")
  syntax on
endif


" To make tabs more readable, the label only contains the tail of the file
" name and the buffer modified flag.
set guitablabel=%M%t


" Send print jobs to Preview.app.  This does not delete the temporary ps file
" that is generated by :hardcopy.
set printexpr=system('open\ -a\ Preview\ '.v:fname_in)\ +\ v:shell_error


" Restore the previous value of 'cpoptions'.
let &cpo = s:cpo_save
unlet s:cpo_save


" An example for a Japanese version gvimrc file.
" 日本語版のデフォルトGUI設定ファイル(gvimrc) - Vim 7.4
"
" Last Change: 01-Jun-2018.
" Maintainer:  MURAOKA Taro <koron.kaoriya@gmail.com>
"
if has('win32')
  " Windows
  set guifont=MS_Gothic:h11
elseif has('mac') || has('unix')
  " Linux
endif
try
  if has('win32')
    " set guifont=VL_ゴシック:h11
    set guifont=Ricty_Diminished:h9:cSHIFTJIS:qDRAFT
    set renderoptions=type:directx,renmode:4
  endif
endtry


set listchars=tab:»\ ,trail:-,eol:↲,extends:»,precedes:«,nbsp:%

" 個別のタブの表示設定をします
function! GuiTabLabel()
  " タブで表示する文字列の初期化
  let l:label = ''

  " タブに含まれるバッファ(ウィンドウ)についての情報をとっておく
  let l:bufnrlist = tabpagebuflist(v:lnum)

  " 表示文字列にバッファ名を追加
  " パスを全部表示させると長いのでファイル名だけを使う
  let l:bufname = fnamemodify(bufname(l:bufnrlist[tabpagewinnr(v:lnum) - 1]), ':t')
  " バッファ名がなければ No title とする
  let l:label .= l:bufname == '' ? 'No title' : l:bufname

  " タブ内にウィンドウが複数あるときにはその数を追加(デフォルトで一応あるので)
  let l:wincount = tabpagewinnr(v:lnum, '$')
  if l:wincount > 1
    let l:label .= '[' . l:wincount . ']'
  endif

  " このタブページに変更のあるバッファがるときには '[+]' を追加します(デフォルトで一応あるので)
  for l:bufnr in l:bufnrlist
    if getbufvar(l:bufnr, "&modified")
      let l:label .= '[+]'
      break
    endif
  endfor

  " 表示文字列を返します
  return l:label
endfunction

" guitablabel に上の関数を設定します
" その表示の前に %N というところでタブ番号を表示させています
set guitablabel=%N:\ %{GuiTabLabel()}

colorscheme lighthouse
