vim.filetype.add({
  pattern = {
    [".*git/config"] = "gitconfig",
    [".*/.pryrc"] = "ruby",
    [".*/.*%.rake"] = "ruby",
    [".*/.*%.schema"] = "ruby",
    [".*/.bashrc"] = "bash",
    [".*/.bash_profile"] = "bash",
    [".*/.bashrc.local"] = "bash",
    [".*/.bash_profile.local"] = "bash",
    [".*/.zshrc"] = "zsh",
    [".*/.zprofile"] = "zsh",
    [".*/.zshrc.local"] = "zsh",
    [".*/.zprofile.local"] = "zsh",
    [".*/.env"] = "bash",
    [".*/.env%..*"] = "bash",
    [".*/%.git/hooks/pre%-commit"] = "bash",
    [".*/.luacheckrc"] = "lua",
    [".*/.*%.log%..*"] = "log",
    [".*/Guardfile"] = "ruby",
  },
})