nmap [rails]m :vs<CR>:<C-u>Emodel 
nmap [rails]M :<C-u>Emodel 
nmap [rails]c :vs<CR>:<C-u>Econtroller 
nmap [rails]C :<C-u>Econtroller 
nmap [rails]h :vs<CR>:<C-u>Ehelper 
nmap [rails]H :<C-u>Ehelper 
nmap [rails]v :vs<CR>:<C-u>Eview 
nmap [rails]V :<C-u>Eview 
nmap [rails]j :vs<CR>:<C-u>Ejavascript 
nmap [rails]J :<C-u>Ejavascript 
nmap [rails]l :<C-u>Clog 
