hi! link tomlEscape      SpecialChar
hi! link tomlLineEscape  SpecialChar
hi! link tomlString      String
hi! link tomlInteger     Number
hi! link tomlFloat       Float
hi! link tomlBoolean     Boolean
hi! link tomlDate        Constant
hi! link tomlComment     Comment
hi! link tomlTable       Comment
hi! link tomlTableArray  Tag
hi! link tomlTodo        Todo
hi! link tomlLabel       Character
