-- vim.g.my_yank = vim.g.my_yank or {""}
-- vim.g.clipboard = {
--   name = "WslClipboard",
--   copy = {
--     ["+"] = "lemonade.exe copy",
--     ["*"] = "lemonade.exe copy",
--   },
--   paste = {
--     ["+"] = "lemonade.exe paste",
--     ["*"] = "lemonade.exe paste",
--   },
--   cache_enabled = 0
-- }
