- name: Install python3-venv package
  become: true
  ansible.builtin.apt:
    name:
      - python3-venv
      - python3-pip
    state: present

- name: Create neovim python venv
  ansible.builtin.command:
    cmd: python3 -m venv {{ ansible_env.HOME }}/.venvs/neovim
    creates: "{{ ansible_env.HOME }}/.venvs/neovim/bin/python3"

- name: Ensure pip is installed in neovim venv
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.venvs/neovim/bin/python3 -m ensurepip --upgrade"
    creates: "{{ ansible_env.HOME }}/.venvs/neovim/bin/pip3"

- name: Install python pip packages in neovim venv
  ansible.builtin.pip:
    name:
      - pynvim
      - neovim
    executable: "{{ ansible_env.HOME }}/.venvs/neovim/bin/pip3"
