- name: Setup local dev environment
  hosts: local
  roles:
    - common
    - dotfiles
    - dotfiles_private
    - pixi
    - herdr
    - ai_tools
    - neovim
    - rust
    - zsh
    - ruby
    - marksman
    - pandoc
